# Generated by Django 2.2.5 on 2019-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20191006_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='container_image',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='scenario_type',
            new_name='scenario',
        ),
        migrations.AddField(
            model_name='track',
            name='final_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='scenario_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
