# Generated by Django 2.2.5 on 2019-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20191006_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='check_script',
            new_name='checkscript',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='clean_script',
            new_name='cleanscript',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='setup_script',
            new_name='setupscript',
        ),
        migrations.AddField(
            model_name='track',
            name='configscript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='installscript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
