# Generated by Django 2.2.5 on 2019-10-12 11:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20191006_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='scenario_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
