# Generated by Django 2.2.5 on 2019-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20191012_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
