# Generated by Django 2.2.5 on 2019-10-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_auto_20191012_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='scenario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
