# Generated by Django 2.2.5 on 2019-10-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_auto_20191012_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='labs.Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='track', to='labs.Topic'),
        ),
    ]
