# Generated by Django 2.2.5 on 2019-10-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_auto_20191013_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('container_id', models.CharField(max_length=100)),
                ('track_id', models.ForeignKey(on_delete='CASCADE', to='labs.Track')),
            ],
        ),
    ]
