# Generated by Django 2.2.5 on 2019-10-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_containerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdata',
            name='container_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
