# Generated by Django 2.2.5 on 2019-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_containerdata_container_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdata',
            name='container_temp',
            field=models.BooleanField(default=True),
        ),
    ]
