# Generated by Django 2.2.5 on 2019-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_auto_20191019_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('submit_status', models.CharField(max_length=100)),
                ('track_id', models.ForeignKey(on_delete='CASCADE', to='labs.Track')),
            ],
        ),
    ]
