# Generated by Django 2.2.5 on 2019-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0013_submittedassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
