# Generated by Django 2.2.5 on 2019-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0015_auto_20191020_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
