# Generated by Django 2.2.5 on 2019-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0016_challenge_challenge_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='no_challenges',
            field=models.BooleanField(default=False),
        ),
    ]
