# Generated by Django 2.2.5 on 2019-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0017_track_no_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='no_challenges',
        ),
    ]
