# Generated by Django 2.2.5 on 2019-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0019_auto_20191023_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submittedassignments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
