# Generated by Django 2.2.5 on 2019-10-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0020_auto_20191023_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdata',
            name='container_run_by_instructor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignments',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
