# Generated by Django 2.2.5 on 2019-10-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0021_auto_20191024_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='graded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='colablink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='labtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
