# Generated by Django 2.2.5 on 2019-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0023_auto_20191026_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdata',
            name='container_colab_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='containerdata',
            name='container_colab_webview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignments',
            name='container_colab_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignments',
            name='container_colab_webview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='containerdata',
            name='container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='containerdata',
            name='container_temp',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='submittedassignments',
            name='container_temp',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
