# Generated by Django 2.2.5 on 2019-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0024_auto_20191026_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignments',
            name='lis_outcome_service_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittedassignments',
            name='lis_result_sourcedid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
