# Generated by Django 2.2.5 on 2019-10-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0025_auto_20191028_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='containerdata',
            unique_together={('track_id', 'course_id', 'student_id')},
        ),
    ]
