# Generated by Django 2.2.5 on 2019-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0026_auto_20191029_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignments',
            name='grade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
