# Generated by Django 2.2.5 on 2019-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0027_auto_20191031_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignments',
            name='lis_result_sourcedid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
